services:
  - type: web
    name: fintech-llm-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn enhanced_fintech_main:app --host 0.0.0.0 --port $PORT
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: HUGGING_FACE_API_TOKEN
        sync: false
      - key: ALPHA_VANTAGE_API_KEY
        sync: false
      - key: FINNHUB_API_KEY
        sync: false
